---
name: hello
on:
  workflow_dispatch:
    
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: say hello to users
        run: echo "hello dosto"
      - name: say hello to username
        run: echo "hello $USER"
        
  details:
    runs-on: ubuntu-latest
    steps:
       - name: version of python, docker, etc
         run: docker --version && python --version
